apiVersion: v1
kind: Pod
metadata:
  name: azure-vote-front
spec:
  containers:
  - name: azure-vote-front
    image: microsoft/azure-vote-front:v1
    ports:
    - containerPort: 80
    env:
    - name: REDIS
      value: "azure-vote-back"